"""
Python bindings for Lean 4 compiled library.
Generated by lean2py. Load with: from this_module import <names>.

"""

import ctypes
import os

_lib_path = os.environ.get(
    "LEAN2PY_LIB",
    'C:/Users/tclay/Documents/projects/bigo-gen/libLeanExport.dll'
)
_lib = None

def _get_lib():
    global _lib
    if _lib is None:
        if not os.path.isfile(_lib_path):
            raise FileNotFoundError(
                f"Lean shared library not found at {_lib_path!r}. "
                "Build it with: uv run lean2py <file.lean> -o <dir> (requires Lean 4 + lake), "
                "or set LEAN2PY_LIB to the path of your .dll/.so/.dylib."
            )
        if hasattr(os, 'add_dll_directory'):
            os.add_dll_directory('c:\\Users\\tclay\\.elan\\toolchains\\leanprover--lean4---v4.27.0\\bin')
        _lib = ctypes.CDLL(_lib_path)
        _init = getattr(_lib, "initialize_lean2py__export_LeanExport", None)
        if _init is not None:
            _init.argtypes = [ctypes.c_uint8]
            _init.restype = ctypes.c_void_p
            _init(0)
    return _lib

_lean_bin_dir = os.environ.get("LEAN2PY_LEAN_BIN", 'c:\\Users\\tclay\\.elan\\toolchains\\leanprover--lean4---v4.27.0\\bin') or None
try:
    from lean2py.lean2py import ffi as _lean_ffi
except ImportError:
    _lean_ffi = None

def mergesort(*args, **kwargs):
    """Call Lean export mergesort. Pass a list of ints for (Array UInt32) -> scalar or array."""
    _lib = _get_lib()
    if _lean_ffi is not None and len(args) == 1 and not kwargs:
        a = args[0]
        if isinstance(a, (list, tuple)) and all(isinstance(x, int) for x in a):
            try:
                return _lean_ffi.call_array_u32_flexible(_lib, None, 'mergesort', list(a), _lean_bin_dir)
            except (AttributeError, NotImplementedError, RuntimeError, ValueError):
                pass
    f = getattr(_lib, 'mergesort', None)
    if f is None:
        raise AttributeError('Lean export not found: mergesort')
    return f(*args, **kwargs)

__all__ = ['mergesort']